// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCMx47moc7hlfvcsNXh-YLRMEQbOc3Z68',
    appId: '1:958254530971:web:e28fda8da052d12f00e13e',
    messagingSenderId: '958254530971',
    projectId: 'amerckcare-9d72a',
    authDomain: 'amerckcare-9d72a.firebaseapp.com',
    storageBucket: 'amerckcare-9d72a.firebasestorage.app',
    measurementId: 'G-W2ZF8K319Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgwX97_lXk24JXFGN4xKsj57EXhPatOjM',
    appId: '1:958254530971:android:48e75ca221f786da00e13e',
    messagingSenderId: '958254530971',
    projectId: 'amerckcare-9d72a',
    storageBucket: 'amerckcare-9d72a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNFBZDy_ASrW0M1ahzAXvfuP7IV_F87P0',
    appId: '1:958254530971:ios:1ca360c47697ab4400e13e',
    messagingSenderId: '958254530971',
    projectId: 'amerckcare-9d72a',
    storageBucket: 'amerckcare-9d72a.firebasestorage.app',
    iosBundleId: 'com.example.amerckcarelogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNFBZDy_ASrW0M1ahzAXvfuP7IV_F87P0',
    appId: '1:958254530971:ios:1ca360c47697ab4400e13e',
    messagingSenderId: '958254530971',
    projectId: 'amerckcare-9d72a',
    storageBucket: 'amerckcare-9d72a.firebasestorage.app',
    iosBundleId: 'com.example.amerckcarelogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCMx47moc7hlfvcsNXh-YLRMEQbOc3Z68',
    appId: '1:958254530971:web:ada8e2c37239659c00e13e',
    messagingSenderId: '958254530971',
    projectId: 'amerckcare-9d72a',
    authDomain: 'amerckcare-9d72a.firebaseapp.com',
    storageBucket: 'amerckcare-9d72a.firebasestorage.app',
    measurementId: 'G-C2NC6N9PHC',
  );
}
